from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4


class MessageRole(StrEnum):
    USER = "user"
    ASSISTANT = "assistant"


@dataclass(slots=True)
class Message:
    """One turn in a conversation.

    `citations` holds the same dicts `build_citations` produces, stored verbatim as JSONB so
    a thread can be re-read months later without re-running retrieval — and so "which
    answers cited this source?" is a containment query rather than a join.

    `insufficient_context` is a first-class outcome, not an error: the assistant answered
    honestly that the library didn't contain enough to work from.
    """

    conversation_id: UUID
    role: MessageRole
    content: str
    id: UUID = field(default_factory=uuid4)
    citations: list[dict[str, Any]] = field(default_factory=list)
    insufficient_context: bool = False
    created_at: datetime | None = None


@dataclass(slots=True)
class Conversation:
    """A named, resumable thread of questions and answers.

    `title` is derived from the opening question rather than generated by a model — the
    extra call isn't worth it, and the first question is usually the best label anyway.
    """

    knowledge_base_id: UUID
    title: str
    id: UUID = field(default_factory=uuid4)
    messages: list[Message] = field(default_factory=list)
    created_at: datetime | None = None
    updated_at: datetime | None = None

    @property
    def message_count(self) -> int:
        return len(self.messages)

    @property
    def preview(self) -> str:
        """Enough of the last exchange to recognise the thread in a list."""
        if not self.messages:
            return ""
        return self.messages[-1].content[:160]
